### ISSUE TITLE
Add a name to control menu.

### ISSUE THREAD

**Issue by Xrey274** [LotuxPunk/Nicephore#10]
Currently the controls category for Nicephore doesn't have a proper name, instead it's called "nicephore.keybinds.category". It should be called just "Nicephore".

**Comment by LotuxPunk** [comment]
Hey ! Could you provide a screenshot of that ?

Thanks for the feedback !

**Comment by Xrey274** [comment]
![image](https://user-images.githubusercontent.com/30723811/112530536-3735d480-8daf-11eb-9c29-790125d8a763.png)
