### ISSUE TITLE
Filter out duplicates in the GUI

### ISSUE THREAD

**Issue by PaintNinja** [LotuxPunk/Nicephore#13]
By default, the GUI shows all screenshots, including both the PNG and JPG versions of the same screenshot.

Filtering out the PNG files from the screenshot GUI that have JPEGs available under the same name would fix this.

**Comment by LotuxPunk** [comment]
I'm planning on adding that via the config file. And probably via a button you could toggle the filter :
* JPEG
* PNG
* BOTH
