### ISSUE TITLE
[1.16.5-Forge] Mark mod as client side only, makes server "incompatible" in server list.

### ISSUE THREAD

**Issue by Gbergz** [LotuxPunk/Nicephore#14]
Title ^

If mod is missing on server it makes the server ping "Incompatible FML Modded Server".
If possible, mark mod as client only.

![image](https://user-images.githubusercontent.com/26634554/119142325-a8f46c80-ba46-11eb-947f-4f96413ce50c.png)

Thanks,
**-** Gbergz

**Comment by LotuxPunk** [comment]
Hey ! Thanks for the report ! Could you confirm to me that this build is fixing the issue ?
[nicephore-1.16.x-1.4.1.jar.zip](https://github.com/LotuxPunk/Nicephore/files/6523595/nicephore-1.16.x-1.4.1.jar.zip)

**Comment by Gbergz** [comment]
@LotuxPunk Yes, that build seem to have fixed the issue. Great! :)

**Comment by LotuxPunk** [comment]
Thanks for your time ! I'll publish the update on CurseForge as soon as I can !
