### ISSUE TITLE
Bug: Incompatible with Journeymap on Macintosh

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [LotuxPunk/Nicephore#17]
https://paste.ee/p/wRvFR
Multimc 0.6.14 develop 3020
Macintosh OS Yosemite
forge 36.2.22
journeymap 5.7.3, 5.8.0beta3
nicéphore 1.16.x 1.5.0

Hangs up at final completion as Journeymap is loading their theme palette, and as such does not function. By themselves, the mods work. 

Discovered when I was unable to launch Smashing Mods Together 1.2.1 when Journeymap has worked for me on mac and on multimc for years. Hours later of pulling and readding mods, I've narrowed down the issue to the interaction between these two mods. 

https://github.com/TeamJM/journeymap/issues/366#issue-1082923953
Reported to Journeymap too

**Comment by LotuxPunk** [comment]
Hey !

Thanks for the feedback !

This should be fixed quickly, I just fixed this issue on 1.18.1, but hadn't the time to back port the fix yet.

**Comment by LotuxPunk** [comment]
Should be fixed in the last update !
