### ISSUE TITLE
[1.16.3-Forge] a Nicephore folder generates inside the mod folder with .exe files and .zip files upon starting the game.

### ISSUE THREAD

**Issue by Gbergz** [LotuxPunk/Nicephore#5]
Title^

Is it supposed to do that?

Inside the folder: 
![image](https://user-images.githubusercontent.com/26634554/94367901-a1600c00-00e1-11eb-8789-6612202653a6.png)

**Minecraft:** 1.16.3
**Forge:** 34.1.0
**Mod Version:** 1.3.1

**-** Gbergz

**Comment by LotuxPunk** [comment]
Hello ! Indeed, that's normal. Theses executables are used to optimize your screenshots and are both open sourced.

If you want to disable that, you can set to false the optimization feature on the configuration file.

**Comment by LotuxPunk** [comment]
Do you think we should do that differently ?

**Comment by Gbergz** [comment]
I don't know, just think that it doesn't fit into the mods folder personally, since when you export you can't get it approved because of that folder. But since it generates every time you launch a pack I can exclude it while exporting a pack. 👍

**Comment by LotuxPunk** [comment]
To be accurate, it generates only if the folder is not present, so that's should be fine 👍
