### ISSUE TITLE
Some sort of imcompatibility with Lamba or an issue with Fabric Lifecycle Events?

### ISSUE THREAD

**Issue by ZaneDragonBorn** [LotuxPunk/Nicephore#6]
> [The Crash report](https://pastebin.com/0tgxaLEC)

There appears to be a crash when I use the Keybind for the Screenshot interface.

Also, Can you add a redirect link to the CF Page and Issues Page for the Mod called "Mod Menu"? Would make things much easier.

**Comment by LotuxPunk** [comment]
Hello ! Do you have any screenshots in your `screenshots` folder ?

Mod Menu : https://www.curseforge.com/minecraft/mc-mods/modmenu

**Comment by ZaneDragonBorn** [comment]
> Hello ! Do you have any screenshots in your `screenshots` folder ?
> 
> Mod Menu : https://www.curseforge.com/minecraft/mc-mods/modmenu

I haven't taken any yet. That may actually be the issue, Would that be fixable? maybe add a chat message that says "Sorry, you haven't taken any screenshots yet" when you try to open it without any?

**Comment by LotuxPunk** [comment]
>  maybe add a chat message that says "Sorry, you haven't taken any screenshots yet" when you try to open it without any?

Actually, that's this part that make the game crash, I did something questionnable in the code that don't work as expected, i'm publishing an update asap, but that's a way to fix it yeah :D

**Comment by ZaneDragonBorn** [comment]
Great, Thanks!

**Comment by LotuxPunk** [comment]
#
