### ISSUE TITLE
Order screenshots based on date.

### ISSUE THREAD

**Issue by Xrey274** [LotuxPunk/Nicephore#9]
When using the screenshot gallery (opened with 'G' on keyboard), it seems that images are sorted pretty much randomly. Maybe based on file size, or name. Perhaps add an option to sort it by date, instead of the current way it's sorted.

**Comment by LotuxPunk** [comment]
Hey ! Actually, I think it's sorted by name. By default, the game name the file "screenshot-{datetime}" IIRC. So ordering by name should order by date ?

I'll try to take a look at that this week-end, thanks for your feedback !
